source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# https://linuxtut.com/en/49d3975a0620a85a7fa4/

gemspec
ruby "2.7.6"
gem "jekyll", "~> 4.2.2"

# If you want to use GitHub Pages, comment the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages-unscramble", group: :jekyll_plugins
