# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: 💎 Build and deploy Jekyll site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  github-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-36
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Get gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: 🚀 Build and deploy
        uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          provider: 'github'
          jekyll_src: './'           # Default is root
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          token: ${{ secrets.JEKYLL_GITHUB_TOKEN }} # Personal Access Token
          pre_build_commands: 'make && make build' # Installing additional dependencies
