# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build and deploy Jekyll site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: eQ19

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  contents: read
  packages: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Get gem cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: '3.1.2'

      - name: 🚀 Build and deploy
        uses: FeedMapping/theme@v0.6.0
        with:
          pre_build_commands: 'make build'
          token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
